---
- hosts: all
  become: true
  vars_prompt:
    - name: "user_name"
      prompt: "Name of the default user"
    - name: "user_password"
      prompt: "Password of the default user"
    - name: "noip_username"
      prompt: "Noip username"
    - name: "noip_password"
      prompt: "Noip password"
  roles:
    - raspbian
    - tools
    - default-users
    - collectd-client
    - docker
- hosts: pi1
  become: true
  roles:
    - nfs-server
    - graphite-server
    - noip
- hosts: pi2,pi3,pi4
  become: true
  roles:
    - nfs-client
