---
- hosts: all
  become: true
  vars_prompt:
    - name: "user_name"
      prompt: "Name of the default user"
    - name: "user_password"
      prompt: "Password of the default user"
  roles:
    - tools
    - default-users
    - collectd-client
- hosts: pi1
  become: true
  roles:
    - nfs-server
    - graphite-server
- hosts: pi2,pi3,pi4
  become: true
  roles:
    - nfs-client
