- name: Comment out the original mirrordirector.raspbian.org mirror.
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^(deb http://mirrordirector.raspbian.org.*$)'
    backrefs: yes
    line: '# \1'
    
- name: Use Hungarian Raspbian mirror
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^deb http://raspbian.innobrand.hu'
    line: 'deb http://raspbian.innobrand.hu/raspbian/ jessie main contrib non-free rpi'
