---
- name: Install graphite pacakges.
  apt: name={{item}} update-cache=yes cache_valid_time=3600
  with_items:
    - graphite-carbon
    - graphite-web
- name: Updates the graphite web config.
  copy:
    src: local_settings.py
    dest: /etc/graphite/local_settings.py
    owner: root
    group: root
    mode: 0644
- name: Initialize the django db. Interactive, create admin / admin user.
  expect:
    command: graphite-manage syncdb
    responses:
      'Would you like to create one now?.*': 'yes'
      'Username.*': 'admin'
      'Email address:.*': 'a@a.hu'
      'Password.*': 'admin'
- name: Update ownership of the graphite db
  file:
    path: /var/lib/graphite/graphite.db
    owner: _graphite
    group: _graphite
- name: Copy initd script.
  copy:
    src: graphite-web
    dest: /etc/init.d/graphite-web
    owner: root
    group: root
    mode: 0755
- name: Add init script symlinks
  command: update-rc.d graphite-web defaults      
- name: Start server
  command: /etc/init.d/graphite-web restart
      
  
  
